export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const COLLABORATOR_REPOSITORY = Symbol('COLLABORATOR_REPOSITORY');
export const SKILL_REPOSITORY = Symbol('SKILL_REPOSITORY');
export const COLLABORATOR_SKILL_REPOSITORY = Symbol(
  'COLLABORATOR_SKILL_REPOSITORY',
);
export const EXPERIENCE_REPOSITORY = Symbol('EXPERIENCE_REPOSITORY');
export const PROJECT_REPOSITORY = Symbol('PROJECT_REPOSITORY');
export const PROJECT_TYPE_REPOSITORY = Symbol('PROJECT_TYPE_REPOSITORY');
export const PROJECT_CATEGORY_REPOSITORY = Symbol(
  'PROJECT_CATEGORY_REPOSITORY',
);
export const PROGRAM_REPOSITORY = Symbol('PROGRAM_REPOSITORY');
